// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.21.12
// source: proto/gallery.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Artwork struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	ThemeId       string                 `protobuf:"bytes,4,opt,name=theme_id,json=themeId,proto3" json:"theme_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // Original EXIF date or upload date
	ImagePath     string                 `protobuf:"bytes,6,opt,name=image_path,json=imagePath,proto3" json:"image_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Artwork) Reset() {
	*x = Artwork{}
	mi := &file_proto_gallery_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Artwork) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Artwork) ProtoMessage() {}

func (x *Artwork) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gallery_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Artwork.ProtoReflect.Descriptor instead.
func (*Artwork) Descriptor() ([]byte, []int) {
	return file_proto_gallery_proto_rawDescGZIP(), []int{0}
}

func (x *Artwork) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Artwork) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Artwork) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Artwork) GetThemeId() string {
	if x != nil {
		return x.ThemeId
	}
	return ""
}

func (x *Artwork) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Artwork) GetImagePath() string {
	if x != nil {
		return x.ImagePath
	}
	return ""
}

type Theme struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Theme) Reset() {
	*x = Theme{}
	mi := &file_proto_gallery_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Theme) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Theme) ProtoMessage() {}

func (x *Theme) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gallery_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Theme.ProtoReflect.Descriptor instead.
func (*Theme) Descriptor() ([]byte, []int) {
	return file_proto_gallery_proto_rawDescGZIP(), []int{1}
}

func (x *Theme) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Theme) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Theme) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

var File_proto_gallery_proto protoreflect.FileDescriptor

const file_proto_gallery_proto_rawDesc = "" +
	"\n" +
	"\x13proto/gallery.proto\x12\agallery\"\xa9\x01\n" +
	"\aArtwork\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x19\n" +
	"\btheme_id\x18\x04 \x01(\tR\athemeId\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\x12\x1d\n" +
	"\n" +
	"image_path\x18\x06 \x01(\tR\timagePath\"M\n" +
	"\x05Theme\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescriptionB$Z\"github.com/brotherlogic/rose/protob\x06proto3"

var (
	file_proto_gallery_proto_rawDescOnce sync.Once
	file_proto_gallery_proto_rawDescData []byte
)

func file_proto_gallery_proto_rawDescGZIP() []byte {
	file_proto_gallery_proto_rawDescOnce.Do(func() {
		file_proto_gallery_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_gallery_proto_rawDesc), len(file_proto_gallery_proto_rawDesc)))
	})
	return file_proto_gallery_proto_rawDescData
}

var file_proto_gallery_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_gallery_proto_goTypes = []any{
	(*Artwork)(nil), // 0: gallery.Artwork
	(*Theme)(nil),   // 1: gallery.Theme
}
var file_proto_gallery_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_gallery_proto_init() }
func file_proto_gallery_proto_init() {
	if File_proto_gallery_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_gallery_proto_rawDesc), len(file_proto_gallery_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_gallery_proto_goTypes,
		DependencyIndexes: file_proto_gallery_proto_depIdxs,
		MessageInfos:      file_proto_gallery_proto_msgTypes,
	}.Build()
	File_proto_gallery_proto = out.File
	file_proto_gallery_proto_goTypes = nil
	file_proto_gallery_proto_depIdxs = nil
}
